redisson:
  #### 自定义的属性
  # 是否开启
  enabled: false
  # redis使用模式
  mode: single # 取值：single, cluster

  #### Config的属性
  config:
    # 线程池数量,默认值: 当前处理核数量 * 2
    threads: 0
    # Netty线程池数量,默认值: 当前处理核数量 * 2
    nettyThreads: 0
    # 编码
    codec: "!<org.redisson.codec.JsonJacksonCodec> {}"
    # 传输模式
    transportMode: "NIO"

  #### SingleServerConfig 和 ClusterServersConfig均有的属性
  baseConfig:
    pingConnectionInterval: 0
    # 连接空闲超时 如果当前连接池里的连接数量超过了最小空闲连接数，而同时有连接空闲时间超过了该数值，那么这些连接将会自动被关闭，并从连接池里去掉。时间单位是毫秒。
    idleConnectionTimeout: 10000
    # 连接超时，单位：毫秒
    connectTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 命令失败重试次数,如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
    # 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
    retryAttempts: 3
    # 命令重试发送时间间隔，单位：毫秒
    retryInterval: 1500
    # 密码
    password:
    # 单个连接最大订阅数量
    subscriptionsPerConnection: 5
    # 客户端名称
    clientName: null
    # 发布和订阅连接的最小空闲连接数
    subscriptionConnectionMinimumIdleSize: 1
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50
    # DNS监测时间间隔，单位：毫秒
    dnsMonitoringInterval: 5000

  #### SingleServerConfig的属性
  singleServerConfig:
    # 节点地址
    address: redis://user:@localhost:6379
    # 最小空闲连接数
    connectionMinimumIdleSize: 32
    # 连接池大小
    connectionPoolSize: 64
    # 数据库编号
    database: 0

  #### ClusterServersConfig的属性
  clusterServersConfig:

    #负载均衡算法类的选择  默认轮询调度算法RoundRobinLoadBalancer
    loadBalancer: "!<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}"
    # 从节点最小空闲连接数
    slaveConnectionMinimumIdleSize: 32
    # 从节点连接池大小
    slaveConnectionPoolSize: 64
    # 主节点最小空闲连接数
    masterConnectionMinimumIdleSize: 32
    # 主节点连接池大小
    masterConnectionPoolSize: 64
    # 只在从服务节点里读取
    readMode: "SLAVE"
    # 主节点信息
    nodeAddresses:
      - "redis://192.168.56.128:7000"
      - "redis://192.168.56.128:7001"
      - "redis://192.168.56.128:7002"
    #集群扫描间隔时间 单位毫秒
    scanInterval: 1000